# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: f14acbc4213482a64eab463f0c2f737acb8281718dda0e4a5b865f1c76cd271e28a41fe69ea21224210086a6dc028da644b8bd9ce1e21e673b00a78aabdec7aa

test:
  secret_key_base: 3ca073daf921ea278ba535ddedfed7c3d63d623302fcc8a0cacdd7ba1af42be580225b37c7cca2681be6e5c9f2eb26159cef4a92d7ed86bd7efb4493d2b297ea

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
